### ISSUE TITLE
Assimilated adventurers no spawning naturally (vanilla SRP bug).

### ISSUE THREAD

**Issue by GrandeMalum** [Nischhelm/SRPMultiplier#11]
Hello, dear developer. Even though default SRP configs (as of v1.9.21) state that assimilated adventurer should naturally spawn starting from evolution phase 2, they don't seem to spawn, even after players dying decent amount of times in the world so it would meet a needed assimilation value, if there is one. Thralls on the other hand seem to have no problems with natural spawning starting from phase 4. Not sure if it's important, but I turn off "Mob Easter Eggs" and set "Mod Easter Egg (Nametags)" value to 0.

**Comment by Nischhelm** [comment]
is that a bug report for SRP? does it happen with/without SRPMixins? Bug reports for SRP go to SRP discord.

Code looks like any other assim mob. 
- Are they in your spawn lists? They are by default. 
- Do you use the "Evolution Custom Spawner"? Is default enabled. 

idk if ive ever seen assim adventurers spawn naturally. maybe it is an SRP bug. but as i said, that doesnt belong in here.

**Comment by GrandeMalum** [comment]
My bad, sorry. I thought that SRPMixins mod was made to fix some of the SRP’s long lasting bugs and errors that weren’t been looked at by the devs. I’ve reported quite a lot during the past few years but most of my reports are being forgotten or just ignored.

**Comment by Nischhelm** [comment]
it is. i see the SRP discord bug reports and decide from there. its not fair to SRP to report bugs of theirs to me instead of them directly.

**Comment by Nischhelm** [comment]
Just tested it and it works with SRPMixins, doesnt work without. So this def belongs to SRP discord

**Comment by Nischhelm** [comment]
nvm the actual issue is that sim_adventurer doesnt have an entry in the coth conversion list, which it cant have, cause players arent minecraft:player or whatever, they literally dont have a registry name. and in base SRP you cant set the min assimilations to 0 since 0 is treated the same as 1.

i was testing with min assimilations = 0, so that worked with SRPMixins, not without. If you want sim_adventurers spawn you need some other mob thats assimilated to sim_adventurers to fulfil the min assimilations value. 

i guess i COULD add a "player" entry to the coth conversion list...

**Comment by Nischhelm** [comment]
made the bug report for you now

**Comment by GrandeMalum** [comment]
Thank you, much love Nischhelm! <3

**Comment by Nischhelm** [comment]
fixed in v2.9.3, uploading rn

**Comment by GrandeMalum** [comment]
So here is the problem. It seems that there is no min assimilation value in the SRParasitesMobs.cfg for Assimilated Adventurers, so setting Fix Sim Adventurer Points to true won't change anything, because of the logic behind the option. And as my tests show they still don't spawn after I've got assimilated for about 10 times.

**Comment by Nischhelm** [comment]
sim adventurers use sim human needed assim value for their threshold. didnt see that at first. next version will give them their own threshold (like spider). but i tested it and it works already, just using the sim human threshold (5 by default). i also checked the assimilation count for sim adventurer and it goes up when a sim adv gets spawned by me getting killed. so idk how youre testing but i feel like youre testing wrong.

**Comment by GrandeMalum** [comment]
Okay tested it some more, it seems that Assimilated Adventurers doesn't spawn if I set "Mod Easter Eggs" in SRParasites.cfg to false. I personally don't like the unserious tone of easter eggs so I always turn those off. It's funny how it actually breaks the Assimilated Adventurers spawning.

**Comment by GrandeMalum** [comment]
Update: I have no idea how and why but I was able to locate two assimilated adventurers randomly while testing. I never seen any new ones spawning again after that though. Maybe something is conflicting inside the mod and is actively preventing them from spawning?

**Comment by Nischhelm** [comment]
just put only the assim adv in the spawn list for one specific phase, set the phase to that phase (srpevo setphase command), kill @e[type=!player] then check what spawns using forge entity list srparasites:*
